name: genelets
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - numpy
  - scipy
  - networkx
  - h5py
  - matplotlib
  - scikit-learn
  - pandas
  - joblib
  - seaborn
  - ipython
  - pip
  - fasttreeshap
  - pip:
      - git+https://github.com/fspinna/borf.git@xai-improvements
