name: SHISMA_env
channels:
  - conda-forge
dependencies:
  - fasttreeshap
  - h5py
  - ipykernel
  - ipython
  - joblib
  - matplotlib
  - networkx
  - numpy
  - pandas
  - parallel
  - pip
  - python
  - scikit-learn
  - scipy
  - seaborn
